services:
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: smartlearning-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
  #     POSTGRES_DB: ${DATABASE_NAME:-smartlearning}
  #   ports:
  #     - "${DATABASE_PORT:-5432}:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - smartlearning-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: smartlearning-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - smartlearning-network
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: smartlearning-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:5000}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - smartlearning-network

volumes:
  postgres_data:

networks:
  smartlearning-network:
    driver: bridge
