# Production docker-compose
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartlearning-db-prod
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - smartlearning-prod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: smartlearning-backend-prod
    restart: always
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - postgres
    networks:
      - smartlearning-prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: smartlearning-frontend-prod
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - smartlearning-prod

volumes:
  postgres_data_prod:

networks:
  smartlearning-prod:
    driver: bridge
